// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcnbrvpbmijsmhyvnngv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjbmJydnBibWlqc21oeXZubmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODc1MTIsImV4cCI6MjA2MDc2MzUxMn0.rVpbQS0t-qB9IE9oejKg874BWn9U5pIGwY7bRhe84kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);